# Site settings
title: Law Office of Andrew Serros
email: gjsyme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Homepage for the Law Office of Andrew Serros.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lawofficeandrewserros.github.io" # the base hostname & protocol for your site
twitter_username: gjsyme
github_username:  gjsyme

# Build settings
markdown: kramdown
